"""The MVP event catalogue — SDD §3.5."""

from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    SHIP_ENTERED = "SHIP_ENTERED"
    JOURNEY_COMPLETED = "JOURNEY_COMPLETED"
    SCAN_PERFORMED = "SCAN_PERFORMED"
    DISCOVERY = "DISCOVERY"
    TRADE_EXECUTED = "TRADE_EXECUTED"
    MARKET_SHIFT = "MARKET_SHIFT"
    COMBAT_STARTED = "COMBAT_STARTED"
    COMBAT_ROUND = "COMBAT_ROUND"
    COMBAT_RESOLVED = "COMBAT_RESOLVED"
    SHIP_DESTROYED = "SHIP_DESTROYED"
    MESSAGE = "MESSAGE"
    TERRITORY_CHANGE = "TERRITORY_CHANGE"
    AP_GRANTED = "AP_GRANTED"
    TEAM_JOINED = "TEAM_JOINED"
    TEAM_LEFT = "TEAM_LEFT"
    HISTORICAL_EVENT = "HISTORICAL_EVENT"
    MISSION_ACCEPTED = "MISSION_ACCEPTED"
    MISSION_COMPLETED = "MISSION_COMPLETED"
    REPUTATION_CHANGED = "REPUTATION_CHANGED"
    TEAM_DEFECTED = "TEAM_DEFECTED"
    KNOWLEDGE_LEARNED = "KNOWLEDGE_LEARNED"
    SIDED_WITH_INCURSION = "SIDED_WITH_INCURSION"
